# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('hicking', 'hicking')], max_length=100)),
                ('is_circular', models.BooleanField()),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('moderate', 'moderate'), ('difficult', 'difficult'), ('very difficult', 'very difficult'), ('expert', 'expert')], max_length=100)),
                ('distance', models.FloatField()),
                ('elevation_up', models.FloatField()),
                ('elevation_down', models.FloatField()),
                ('max_altitude', models.FloatField()),
                ('min_altitude', models.FloatField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
