# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161221_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='technical_difficulty',
            field=models.IntegerField(choices=[(1, 'easy'), (2, 'moderate'), (3, 'difficult'), (4, 'very difficult'), (5, 'expert')]),
        ),
    ]
