version: "2"
services:
    api:
        image: api:1.0
        container_name: api
        ports:
            - "8000:8000"
        environment:
            - "PRETTYLOC_API_USER=postgres"
            - "PRETTYLOC_API_HOST=postgres"
            - "PRETTYLOC_API_PORT=5432"
        networks:
            - prettyloc-network
        command: bash -c "/myvenv/bin/python3 manage.py migrate && /myvenv/bin/python manage.py scraproute 6374193 && /myvenv/bin/python3 manage.py runserver 0.0.0.0:8000 "
    postgres:
        image: postgres:1.0
        container_name: postgres
        environment:
            - "POSTGRES_DB=prettyloc"
        ports:
            - "5492:5432"
        networks:
            - prettyloc-network

networks:
    prettyloc-network:
        driver: bridge

