from django.contrib.gis.geos import Point, LineString


def generate_line(gpx_lat, gpx_lon):
    points = []
    for i in range(len(gpx_lat)):
        points.append(Point(gpx_lon[i], gpx_lat[i]))
    return LineString(points)


def generate_gpx(title, gpx_lat, gpx_lon):
    gpx = '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>'
    gpx += '<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" creator="Oregon 400t" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd">'
    gpx += '<trk>'
    gpx += '<name>{}</name>'.format(title)
    gpx += '<trkseg>'

    for i in range(len(gpx_lat)):
        gpx += '<trkpt lat="{}" lon="{}">'.format(gpx_lat[i], gpx_lon[i])
        gpx += '</trkpt>'
    gpx += '</trkseg>'
    gpx += '</trk>'
    gpx += '</gpx>'

    return gpx


activities_en = [
    'mountain-biking',
    'hiking',
    'cycling',
    'running',
    'trail-running',
    'mountaineering',
    'bicycle-touring',
    'walking',
    'motorcycling',
    'back-country-skiing',
    'trail-bike',
    'atv',
    'kayaking-canoeing',
    'sailing',
    'snowshoeing',
    'cross-country-skiing',
    'alpine-skiing',
    'flying',
    'horseback-riding',
    'dog-sledging',
    'rock-climbing',
    'inline-skating',
    'skating',
    'train',
    'canyoneering',
    'diving',
    'caving',
    'hang-gliding',
    'ballooning',
    'snowboarding',
    'ice-climbing',
    'snowmobiling',
    'accessible',
    'offroading',
    'rowing',
    'car',
    'kiteboarding',
    'kite-skiing',
    'sledge',
    'kickbike',
    'paragliding',
    'for-blind',
    'nordic-walking',
    'motorcycle-trials',
    'enduro',
    'via-ferrata',
    'swimming',
    'orienteering',
    'multisport',
    'stand-up-paddle-sup',
    'barefoot',
    'canicross',
    'roller-skiing',
    'longboarding',
    'mountain-unicycling',
    'golf',
    'recreational-vehicle',
    'airboat',
    'segway',
    'camel',
    'freeride',
    'unmanned-aerial-vehicle-uav',
    'motorboat',
    'birdwatching-birding',
    'trailer-bike',
    'water-scooter-pwc',
    'handbike',
    'rafting',
    'downhill-mountain-biking-dh',
    'electric-vehicle',
    'base-jumping',
    'joelette',
    'with-baby-carriage',
    'splitboard',
    'cyclocross',
]

activities_es = [
    'mountain-bike',
    'senderismo',
    'ciclismo',
    'carrera',
    'carrera-por-montana',
    'alpinismo',
    'cicloturismo',
    'a-pie',
    'motociclismo',
    'esqui-de-montana',
    'moto-trail',
    'quad',
    'kayac',
    'vela',
    'raquetas',
    'esqui-de-fondo',
    'esqui',
    'avion',
    'a-caballo',
    'trineo-de-perros',
    'escalada',
    'patines-en-linea',
    'patines',
    'tren',
    'descenso-de-barrancos',
    'submarinismo',
    'espeleologia',
    'ala-delta',
    'globo',
    'snowboard',
    'escalada-invernal',
    'moto-de-nieve',
    'sendero-accesible',
    'todo-terreno',
    'remo',
    'coche',
    'kiteboarding',
    'kite-skiing',
    'trineo',
    'kickbike',
    'parapente',
    'para-invidentes',
    'marcha-nordica',
    'moto-trial',
    'moto-enduro',
    'via-ferrata',
    'natacion',
    'orientacion',
    'prueba-combinada',
    'stand-up-paddle-sup',
    'correr-descalzo',
    'canicross',
    'skiroll',
    'longboarding',
    'monociclismo-de-montana',
    'golf',
    'autocaravana',
    'hidrodeslizador',
    'segway',
    'a-camello',
    'freeride',
    'vehiculo-aereo-no-tripulado-dron',
    'lancha-motora',
    'observacion-de-aves',
    'bicicleta-con-remolque',
    'moto-de-agua',
    'handbike',
    'descenso-de-rios-rafting',
    'descenso-mtb',
    'vehiculo-electrico',
    'salto-base',
    'joelette',
    'con-cochecito',
    'splitboard',
    'ciclocross',
]
